In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
x = np.ones((3,3))
x

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [6]:
y = np.zeros((3,3))
y

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## Q#3: Add x and y arrays.

In [7]:
a = x + y
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [8]:
print(type(x))
print(x.ndim)
print(x.shape)
print(x.size)
print(x.dtype)

<class 'numpy.ndarray'>
2
(3, 3)
9
float64


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [9]:
w = np.array([[11,12],[13,14],[15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [10]:
z = np.arange(1,4)
z

array([1, 2, 3])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [11]:
l = w.reshape(2,3)
l
newArray = np.vstack((l,z))
newArray

array([[11, 12, 13],
       [14, 15, 16],
       [ 1,  2,  3]])

## Q#8: Print all elements of "newArray" using the loop.

In [12]:
for i in newArray:
    for j in i:
        print(j)

11
12
13
14
15
16
1
2
3


## Q#9: Reverse the columns and rows of "newArray".

In [13]:
newArray.transpose()

array([[11, 14,  1],
       [12, 15,  2],
       [13, 16,  3]])

## Q#10: Decrement all elements of "newArray" with 1.

In [14]:
newArray -= 1
newArray

array([[10, 11, 12],
       [13, 14, 15],
       [ 0,  1,  2]])

## Q#11: Find smallest and biggest values in "newArray".

In [15]:
j = newArray.min()
p = newArray.max()
print(j,p)

0 15


## Q#12: Print the first row of "newArray" using indexing.

In [16]:
newArray[0]

array([10, 11, 12])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [17]:
b = newArray.ravel()
b
b[2]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [18]:
newArray

array([[10, 11, 12],
       [13, 14, 15],
       [ 0,  1,  2]])

In [19]:
newArray[1: ,0:1]

array([[13],
       [ 0]])

## Q#15: Change the shape of "newArray" to (9,1).

In [20]:
newArray.reshape(9,1)

array([[10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [ 0],
       [ 1],
       [ 2]])

## Q#16: Change the shape of "newArray" to (3,2).

In [ ]:
we can`t because it`s has 9 elements 

# Well Done 🎉